name: first demo 
on:
 push:
  branches: 
  - main 
jobs:
  demo_job:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - name: run a one-line script
      run: echo hello
    - name: run multiple-line script
      run: echo add two line content
